version: "3"
services:
    conflator:
        container_name: conflator
        build: ..
        image: conflator
        volumes:
            - ~\source\garden\conflate\:/data/
            - ~\source\garden\jsons\:/jsons/
            - ~\source\garden\rss\:/rss/
        environment:
            - PERIOD=5m
        depends_on:
            - "overpass"
    overpass:
        container_name: overpass-turbo.eu
        image: wiktorn/overpass-api:0.7.56.4
        environment:
            - OVERPASS_META=yes
            - OVERPASS_MODE=init
            - OVERPASS_PLANET_URL=https://download.geofabrik.de/europe/croatia-latest.osm.bz2
#            - OVERPASS_DIFF_URL=https://download.geofabrik.de/europe/croatia-updates/
        volumes:
            - ~\source\garden\overpass\:/db
        ports:
          - "8000:80"
    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - ~\source\garden\rss\:/usr/share/nginx/html/rss/
        ports:
          - "8080:80"

